export const MESSAGE_ACTIONS = {
  CREATE_MESSAGE: "CREATE_MESSAGE",
  UPDATE_MESSAGE: "UPDATE_MESSAGE",
  REMOVE_MESSAGE: "REMOVE_MESSAGE",
  ADD_MESSAGES: "ADD_MESSAGES",
  RESET_MESSAGES: 'RESET_MESSAGES'
};