export const ROOM_ACTIONS = {
  CREATE_ROOM: 'CREATE_ROOM',
  REMOVE_ROOM: 'REMOVE_ROOM',
  ADD_ROOM: 'ADD_ROOM',
  UPDATE_ROOM: 'UPDATE_ROOM',
  SET_CURRENT_ROOM: 'SET_CURRENT_ROOM',
  RESET_ROOMS: 'RESET_ROOMS'
};